apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: vdns-env-config
    envs:
      - vdns/config.env

secretGenerator:
  - name: vdns-certificate
    files:
      - vdns-certificate/cert.pem
      - vdns-certificate/key.pem

resources:
  - vdns/deployment.yaml
  - vdns/service.yaml

images:
  - name: vdns
    newName: ghcr.io/ah-dark/vdns
    newTag: 0.1.0
