apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdns
  labels:
    app: vdns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vdns
  template:
    metadata:
      name: vdns
      labels:
        app: vdns
    spec:
      volumes:
        - name: certificates
          secret:
            secretName: vdns-certificate
      containers:
        - name: vdns
          image: vdns
          args:
            - "/app/certificates/cert.pem"
            - "/app/certificates/key.pem"
          volumeMounts:
            - mountPath: /app
              name: certificates
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: vdns-env-config
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 853
              protocol: TCP
            - containerPort: 853
              protocol: UDP
            - containerPort: 9090
              protocol: TCP
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
