apiVersion: v1
kind: Service
metadata:
  name: vdns
spec:
  selector:
    app: vdns
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns
    - protocol: TCP
      port: 853
      targetPort: 853
      name: dot
    - protocol: UDP
      port: 853
      targetPort: 853
      name: doq
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: prometheus
